import MpmStaticAd from '../components/ads/MpmStaticAd.jsx'
import { BOOKING_URL } from '../constants/site.js'
import '../styles/mpm-static-ad-export.css'

const PHONE_DISPLAY = '(609) 933-3526'
const PHONE_TEL = 'tel:6099333526'
const SITE = 'mpmnewjersey.com'
const AREA = 'Cherry Hill · Marlton · Moorestown'

/** Backgrounds in public/ads/landscaping/ (JPG). Replace files anytime — photos are not generated by code. */
const PLATES = {
  hero: '/ads/landscaping/mpm-land-01-hero.jpg',
  install: '/ads/landscaping/mpm-land-02-install.jpg',
  lawn: '/ads/landscaping/mpm-land-03-lawn.jpg',
}

export default function LandscapingAdsPage() {
  return (
    <div className="mpm-static-ads-route">
      <p className="page-title">
        Native 1080×1350 plates + React overlay (photo unchanged). Export: Chrome full-size screenshot at
        100% zoom. Save backgrounds as the three filenames in public/ads/landscaping/ — see README there.
      </p>

      <MpmStaticAd
        ratio="4x5"
        bgUrl={PLATES.hero}
        scrim="deep"
        eyebrow="MPM · Landscaping · South Jersey"
        headlineClass="headline-md"
        headline={
          <>
            Curb appeal that
            <br />
            <em>reads from the street.</em>
          </>
        }
        subhead="Mulch, bed edges, plantings — finished like the homes we work on every week."
        chips={['Free estimate', 'Same crew as hardscape', 'Local installs']}
        ctaLabel="Book free estimate"
        bookingUrl={BOOKING_URL}
        phoneDisplay={PHONE_DISPLAY}
        phoneTel={PHONE_TEL}
        siteUrl={SITE}
        serviceArea={AREA}
        adTag="MPM-LAND-01 · 4:5 · hero curb"
      />

      <MpmStaticAd
        ratio="4x5"
        bgUrl={PLATES.install}
        scrim="side"
        eyebrow="MPM · Landscaping services"
        headlineClass="headline-sm"
        headline={
          <>
            Halfway there —
            <br />
            <em>already cleaner.</em>
          </>
        }
        subhead="Fabric, grading, mulch, plantings — one crew through completion, not a dump-and-run."
        chips={['Bed installs', 'Refresh & mulch', 'Clean machine edges']}
        ctaLabel="Book now"
        bookingUrl={BOOKING_URL}
        phoneDisplay={PHONE_DISPLAY}
        phoneTel={PHONE_TEL}
        siteUrl={SITE}
        serviceArea={AREA}
        adTag="MPM-LAND-02 · 4:5 · install progress"
      />

      <MpmStaticAd
        ratio="4x5"
        bgUrl={PLATES.lawn}
        scrim="bottom"
        eyebrow="MPM · South Jersey lawns"
        headlineClass="headline-lg"
        headline={
          <>
            Quiet
            <br />
            <em>finish.</em>
          </>
        }
        subhead="Stripes, edges, beds — maintained like you mean it. Book a walkthrough and we’ll price the scope."
        chips={['Seasonal programs', 'Detail edges', 'Owner on site']}
        ctaLabel="Get free estimate"
        bookingUrl={BOOKING_URL}
        phoneDisplay={PHONE_DISPLAY}
        phoneTel={PHONE_TEL}
        siteUrl={SITE}
        serviceArea={AREA}
        adTag="MPM-LAND-03 · 4:5 · lawn stripes"
      />
    </div>
  )
}
